### ISSUE TITLE
AttributeError: 'Button' object has no attribute 'when_relesed'

### ISSUE THREAD

**Issue by dgshue** [Luca8991/XPT2046-Python#2]
There seems to be a few issues, this being one of them.  Not sure if it's my version of gpiozero or what.  Disabling the line gets passed the error, but I get no output from the test script.

I also get another message as well:

Traceback (most recent call last):
  File "touch-test.py", line 19, in <module>
    xpt = Touch(spi, cs=cs, int_pin=irq, int_handler=touchscreen_press)
  File "/home/pi/XPT2046-Python/xpt2046.py", line 38, in __init__
    self.cs.direction = digitalio.Direction.OUTPUT
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 131, in __setattr__
    self.__class__.__name__, name))
AttributeError: 'DigitalOutputDevice' object has no attribute 'direction'

gpiozero - 1.6.2
Adafruit-Blinka -  6.13.0

**Comment by ilbertt** [comment]
The second error you get seems to be the same of #1. It seems the new `gpiozero` versions have some changes.
You can try removing errors using the (partial) @mattmo92270's solution at https://github.com/Luca8991/XPT2046-Python/issues/1#issuecomment-769405795.
Let me know if you find a better solution.

**PRs are welcome!**

**Comment by ilbertt** [comment]
closed with #3
